language: php

php:
    - "7.4"
    #- "8.0"
env:
  - GUZZLEHTTP="^6.3"
  - GUZZLEHTTP="^7.0"
    #- GUZZLEHTTP="^7.3"

before_script:
  - echo "xdebug.mode=coverage" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/ci.ini
  - composer require guzzlehttp/guzzle:${GUZZLEHTTP} --no-update
  - composer install --prefer-dist --dev

after_script:
  - travis_retry php vendor/bin/php-coveralls
